### ISSUE TITLE
After using Sophie-List, the x64 forum does not open.

### ISSUE THREAD

**Issue by KevinGu0611** [Natsuki-Kaede/Sophie-List#1]
As shown in the figure, the filter log is, and the x64 forum URL is: https://home.x64bbs.cn/
![image](https://user-images.githubusercontent.com/107782505/215318907-31a56691-1578-412d-9ae1-65f6388e0a29.png)

**Comment by Natsuki-Kaede** [comment]
This site may be on blacklist due to unsafe/fraud/spam problem, we will check as soon as possible.
Before this, you can access by adding whitelist.
